### ISSUE TITLE
Ambiguous argument 'HEAD' running rake newclear task

### ISSUE THREAD

**Issue by bigtunacan** [IconoclastLabs/newclear#8]
When I run the `rake newclear` task it errors out.  It looks like it is some type of error interacting with git, but not sure what could be causing this.  I've included the error dump below.

```
Cleaning Project...
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
rake aborted!
ArgumentError: wrong number of arguments (2 for 1)
/Users/jseeley/.rvm/gems/ruby-2.2.1/gems/motion-gradle-2.0.1/lib/motion/project/gradle.rb:49:in `dependency'
/code/rubymotion/myapp/Rakefile:33:in `block (2 levels) in <top (required)>'
/Users/jseeley/.rvm/gems/ruby-2.2.1/gems/motion-gradle-2.0.1/lib/motion/project/gradle.rb:16:in `instance_eval'
/Users/jseeley/.rvm/gems/ruby-2.2.1/gems/motion-gradle-2.0.1/lib/motion/project/gradle.rb:16:in `gradle'
/code/rubymotion/myapp/Rakefile:31:in `block in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `call'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `block in setup'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `each'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `setup'
/Library/RubyMotion/lib/motion/project/app.rb:66:in `config'
/Library/RubyMotion/lib/motion/project.rb:49:in `block in <top (required)>'
/Library/RubyMotion/lib/motion/project.rb:55:in `block (2 levels) in <top (required)>'
/Users/jseeley/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/jseeley/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => clean
(See full trace by running task with --trace)

Bundling...

Setting up gradle automation dependencies...
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
rake aborted!
ArgumentError: wrong number of arguments (2 for 1)
/Users/jseeley/.rvm/gems/ruby-2.2.1/gems/motion-gradle-2.0.1/lib/motion/project/gradle.rb:49:in `dependency'
/code/rubymotion/myapp/Rakefile:33:in `block (2 levels) in <top (required)>'
/Users/jseeley/.rvm/gems/ruby-2.2.1/gems/motion-gradle-2.0.1/lib/motion/project/gradle.rb:16:in `instance_eval'
/Users/jseeley/.rvm/gems/ruby-2.2.1/gems/motion-gradle-2.0.1/lib/motion/project/gradle.rb:16:in `gradle'
/code/rubymotion/myapp/Rakefile:31:in `block in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `call'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `block in setup'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `each'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `setup'
/Library/RubyMotion/lib/motion/project/app.rb:66:in `config'
/Users/jseeley/.rvm/gems/ruby-2.2.1/gems/motion-gradle-2.0.1/lib/motion/project/gradle.rb:223:in `block (2 levels) in <top (required)>'
/Users/jseeley/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/jseeley/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => gradle:install
(See full trace by running task with --trace)
Building project...
for device
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
rake aborted!
ArgumentError: wrong number of arguments (2 for 1)
/Users/jseeley/.rvm/gems/ruby-2.2.1/gems/motion-gradle-2.0.1/lib/motion/project/gradle.rb:49:in `dependency'
/code/rubymotion/myapp/Rakefile:33:in `block (2 levels) in <top (required)>'
/Users/jseeley/.rvm/gems/ruby-2.2.1/gems/motion-gradle-2.0.1/lib/motion/project/gradle.rb:16:in `instance_eval'
/Users/jseeley/.rvm/gems/ruby-2.2.1/gems/motion-gradle-2.0.1/lib/motion/project/gradle.rb:16:in `gradle'
/code/rubymotion/myapp/Rakefile:31:in `block in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `call'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `block in setup'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `each'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `setup'
/Library/RubyMotion/lib/motion/project/app.rb:66:in `config'
/Library/RubyMotion/lib/motion/project/template/android.rb:37:in `block in <top (required)>'
/Library/RubyMotion/lib/motion/project/template/android.rb:759:in `block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/template/android.rb:759:in `each'
/Library/RubyMotion/lib/motion/project/template/android.rb:759:in `block in <top (required)>'
/Users/jseeley/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/jseeley/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => build
(See full trace by running task with --trace)
```

**Comment by GantMan** [comment]
please try the following commands and let me know which one errors:

```
rake clean:all
rake gradle:install
rake

```

**Comment by bigtunacan** [comment]
@GantMan 

It appears to come from the default `rake` task.  I've included the output from the other two below, but don't believe they are in issue; it appears they succeed.

I mentioned the issue here on bluepotion infinitered/bluepotion#104 as I wasn't sure which project this should be filed under.

`rake clean:all` gives the following output

```
fatal: Not a git repository (or any of the parent directories): .git
    Delete ./build
    Delete /Users/jseeley/Library/RubyMotion/build
    Delete vendor/Gradle
```

`rake gradle:install` gives this input

```
fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by gregmolnar** [comment]
@bigtunacan create a git repo for your project. if you look at the Rakefile, you will see it gets the version code from the commits.
